### ISSUE TITLE
TypeError: Object [object Object] has no method 'execSync'

### ISSUE THREAD

**Issue by kations** [Justin-Credible/cordova-plugin-braintree#11]
Get the following Error on install:

Failed to install 'cordova-plugin-braintree':TypeError: Object [object Object] has no method 'execSync'
Line: after_plugin_install.js:10:19

Did i have to install something?

Thanks!

**Comment by thirtified** [comment]
This is most likely caused by an outdated node.js version. I am not sure what version is required, but a version >= 0.12 should work.

**Comment by Justin-Credible** [comment]
That is correct, it looks like `execSync(...)` is available in node 0.12 and newer. I'll update the readme.
