### ISSUE TITLE
getting compile error when creating payment nonce

### ISSUE THREAD

**Issue by kpitorg** [Justin-Credible/cordova-plugin-braintree#12]
So I installed braintree using npm install braintree and it sits under node_modules directory now. There is no typescript file associated to it as it is a pure javascript library.

So not sure how do I import it like I import moment.js using statement: import moment = require('moment'); I found your braintree.d.ts file Do I have to include it somewhere? Is this file even relevant or I can use the braintree JS library directly. Is it even possible to use braintree with ionic2 at the moment? Sorry for so many questions, I am new to typescript and still trying to learn it. Thanks for your time.

**Comment by Justin-Credible** [comment]
I'm not sure about the npm part (the braintree package on npm is unrelated to this plugin), but to install the plugin you'd use:

`cordova plugin add cordova-plugin-braintree`

If you are using TypeScript you could then reference the type definitions from `typings/cordova-plugin-braintree.d.ts`.
