### ISSUE TITLE
Dyld Message: Library not loaded: @rpath/BraintreeVenmo.framework/BraintreeVenmo

### ISSUE THREAD

**Issue by bgizdov** [Justin-Credible/cordova-plugin-braintree#13]
Hi,

I am trying to integrate cordova-plugin-braintree into ionic project. 

After installing the plugin I got the following error:

> $ ionic plugin add cordova-plugin-braintree
> Fetching plugin "cordova-plugin-braintree" via npm
> Installing "cordova-plugin-braintree" for android
> npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
> Installing "cordova-plugin-braintree" for ios
> Error: Path must be a string. Received undefined

And then after run the app on iOS device it crashes:

> Sep 23 02:33:41 My-iPhone SpringBoard[58] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
> Sep 23 02:33:41 My-iPhone SpringBoard[58] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
> Sep 23 02:33:41 My-iPhone kernel[0] <Notice>: xpcproxy[8205] Container: /private/var/mobile/Containers/Data/Application/10832680-702A-45C8-A6CD-90006011E090 (sandbox)
> Sep 23 02:33:41 My-iPhone com.apple.xpc.launchd[1](UIKitApplication:com.ionicframework.ionictest948709[0xf5f6][8205]) <Notice>: Service exited due to signal: Trace/BPT trap: 5
> Sep 23 02:33:41 My-iPhone assertiond[67] <Warning>: Unable to obtain a task name port right for pid 8205: (os/kern) failure (5)
> Sep 23 02:33:41 My-iPhone SpringBoard[58] <Warning>: Unable to register for exec notifications: No such process
> Sep 23 02:33:41 My-iPhone SpringBoard[58] <Warning>: Unable to obtain a task name port right for pid 8205: (os/kern) failure (5)
> Sep 23 02:33:41 My-iPhone SpringBoard[58] <Warning>: Unable to obtain a task name port right for <FBApplicationProcess: 0x154972b20; com.ionicframework.ionictest948709; pid: 8205>
> Sep 23 02:33:41 My-iPhone SpringBoard[58] <Warning>: Application 'UIKitApplication:com.ionicframework.ionictest948709[0xf5f6]' crashed.
> Sep 23 02:33:41 My-iPhone ReportCrash[8206] <Notice>: Formulating report for corpse[8205] MyApp
> Sep 23 02:33:42 My-iPhone SpringBoard[58] <Warning>: Application '(null)' exited for an unknown reason.
> Sep 23 02:33:42 My-iPhone ReportCrash[8206] <Warning>: Saved type '109(109_MyApp)' report (18 of max 25) at /var/mobile/Library/Logs/CrashReporter/MyApp-2016-09-23-023342.ips

Log file:

> Incident Identifier: D95B4B92-EF01-4A1A-AF94-D3E97FB3BDC5
> CrashReporter Key:   eef4fa4568ad203e6d131621ca4adb459a87de72
> Hardware Model:      iPhone7,2
> Process:             MyApp [8205]
> Path:                /private/var/containers/Bundle/Application/2A6D582D-D7F5-442B-ABDD-F8F43DA029A3/MyApp.app/MyApp
> Identifier:          com.ionicframework.ionictest948709
> Version:             0.0.1 (0.0.1)
> Code Type:           ARM (Native)
> Parent Process:      launchd [1]
> 
> Date/Time:           2016-09-23 02:33:41.41 +0300
> Launch Time:         2016-09-23 02:33:41.41 +0300
> OS Version:          iOS 9.3.5 (13G36)
> Report Version:      105
> 
> Exception Type:  EXC_BREAKPOINT (SIGTRAP)
> Exception Codes: 0x0000000000000001, 0x00000000e7ffdefe
> Triggered by Thread:  0
> 
> Filtered syslog:
> None found
> 
> Dyld Error Message:
> Dyld Message: Library not loaded: @rpath/BraintreeVenmo.framework/BraintreeVenmo
>   Referenced from: /var/containers/Bundle/Application/2A6D582D-D7F5-442B-ABDD-F8F43DA029A3/MyApp.app/MyApp
>   Reason: image not found
>   Dyld Version: 390.7
> 
> Binary Images:
> 0x30000 - 0x6bfff MyApp armv7  <44c5f74428f43f7d9b20599fab7019fb> /var/containers/Bundle/Application/2A6D582D-D7F5-442B-ABDD-F8F43DA029A3/MyApp.app/MyApp
> 0x1fe4c000 - 0x1fe73fff dyld armv7s  <023542032680372f8d383c4c2b42a8a3> /usr/lib/dyld

Hmm I saw the issue, it looks that BraintreeVenmo.framework is missing. I will not use Venmo, but I am not sure how to disable it or add the library to cordova.

**Comment by bgizdov** [comment]
The problem was that all of the braintree frameworks cannot be found on runtime.
To solve the issue I added Copy Files of Frameworks in Build Phases in the XCode project settings.

**Comment by Justin-Credible** [comment]
Thanks for the heads up. This should be handled automatically by the new build hook.
