### ISSUE TITLE
Error: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by mikegleasonjr** [Justin-Credible/cordova-plugin-braintree#15]
```
$ cordova plugin add cordova-plugin-braintree
Fetching plugin "cordova-plugin-braintree" via npm
Installing "cordova-plugin-braintree" for browser
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
Installing "cordova-plugin-braintree" for ios
Error: Path must be a string. Received undefined
```

```
$ node --version
v6.6.0
```

```
$ cordova --version
6.3.1
```

**Comment by mikegleasonjr** [comment]
I could use the library anyway, I was just wondering what happened.

**Comment by Justin-Credible** [comment]
I haven't tried with Cordova 6.x (I'm on 5.x) so it could be related to that.

Maybe something with the build hook?

**Comment by jamesdixon** [comment]
@mikegleasonjr did you figure this out? also running into this when building

**Comment by Justin-Credible** [comment]
This happens for me on Node 6.6.0 (but not 4.2.2) from the following block in the build script:
https://github.com/Justin-Credible/cordova-plugin-braintree/blob/master/hooks/after_plugin_install.js#L54

**Comment by mikegleasonjr** [comment]
@jamesdixon It is still working so didn't bother further

**Comment by jamesdixon** [comment]
@Justin-Credible also can confirm that this works on Node 4.x

**Comment by jamesdixon** [comment]
Actually, I take it back -- it seems to be affected by other environmental factors. Still trying to figure out he toor cause.

**Comment by jamesdixon** [comment]
@Justin-Credible I tracked the issue down to the `node-xcode` fork being used. I switched back to the original repo to see if things would work and in fact, it did resolve the issue. However, I know that you used the fork for a reason (as mentioned in #3), so I'm not sure of the effect it will have on the plugin. 

Regardless, it seems like an upgrade is in order that might resolve some of these issues. I've to help!

**Comment by jamesdixon** [comment]
Another update: while I was able to get the build working by switching the `node-xcode` repo, an error is thrown when firing up the app. After further investigation, it appears those changes in the fork were never submitted as a PR

**Comment by Taracque** [comment]
You can try my version, it works for me https://github.com/Taracque/cordova-plugin-braintree
node: v4.6.2
ionic: 2.1.12, ionic lib version: 1.3.2
cordova CLI: 6.4.0

**Comment by jamesdixon** [comment]
@Taracque much appreciated! I'll give this a shot.

**Comment by Justin-Credible** [comment]
@Taracque @jamesdixon Thanks for the information! I also just updated the plugin to 0.5.1 which re-worked the build hook.

I've tested on Node v4.2.2 and v6.6.0 with Cordova v6.4.0 and it is working. Going to close this for now.

**Comment by jamesdixon** [comment]
@Taracque unfortunately, still running into build issues. Seeing the following error using the master branch of your fork:

```
The following build commands failed:

	CompileC /Users/jamesdixon/Library/Developer/Xcode/DerivedData/Scout_Customer-bulfzcppmxbrkmgccfwfdgdizgxr/Build/Intermediates/Scout\ Customer.build/Release-iphonesimulator/Scout\ Customer.build/Objects-normal/i386/BraintreePlugin.o Scout\ Customer/Plugins/cordova-plugin-braintree/BraintreePlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/jamesdixon/Projects/scout/platform/customer-mobile/platforms/ios/cordova/build-release.xcconfig,-workspace,Scout Customer.xcworkspace,-scheme,Scout Customer,-configuration,Release,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 5s,build,CONFIGURATION_BUILD_DIR=/Users/jamesdixon/Projects/scout/platform/customer-mobile/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/jamesdixon/Projects/scout/platform/customer-mobile/platforms/ios/build/sharedpch
```
Any thoughts?

Thank you!

**Comment by jamesdixon** [comment]
@Taracque would you mind detailing your build process? Trying to figure out if this is an environment issue. Much appreciated!
