### ISSUE TITLE
"Proceed with Sandbox Purchase" is not working

### ISSUE THREAD

**Issue by championboylay** [Justin-Credible/cordova-plugin-braintree#23]
When I click PayPal button, https//checkout.paypal.com is opend via external browser. I clicked the "**Proceed with Sandbox Purchase**" but it happens nothing. 

**Pay With a Card** is worked

**Comment by Taracque** [comment]
What you mean on "happens nothing"? Did the paypal window closed? If not there is something wrong with PayPal setup, as the PayPal window itself is not handled by the plugin.
Is it iOS or Android?

**Comment by championboylay** [comment]
It is on Android. Paypal window does not close. When I click the ""Proceed with Sandbox Purchase", it should go back to application. Is it right?

At Drop-in Payment UI , paypal button redirects to [https://checkout.paypal.com/pwpp/2.30.0/html/braintree-frame.html](https://checkout.paypal.com/pwpp/2.30.0/html/braintree-frame.html)
At plugin, paypal button redirect to [https://checkout.paypal.com/one-touch-login-sandbox/index.html](https://checkout.paypal.com/one-touch-login-sandbox/index.html)
I would like to know why they are not same.
Is it the issue, one touch payment is not currently available in my country?

**Comment by Taracque** [comment]
Are you using presentDropInPaymentUI call?
Can you post some code how your code is working?
Do you have Accept PayPal enabled in your Breaintree sandbox Processing Options?

**Comment by championboylay** [comment]
`				
		
			
                BraintreePlugin.initialize(token,
                    function() { console.log("init OK!"); },
                    function(error) { console.error(error); });

                var options = {
                    cancelText: "Cancel",
                    title: "Purchase",
                    ctaText: "Select Payment Method",
                    amount: $rootScope.final_price,
                    primaryDescription: "Your Item",
                    secondaryDescription: "Free shipping!"
                };

                BraintreePlugin.presentDropInPaymentUI(options, function(result) {
                    console.log(result);
                    if (result.userCancelled) {
                        console.debug("User cancelled payment dialog.");
                    } else {
                       // my other tasks
                    }
                });`

When user clicks checkout, I used the above code.
I have also selected "Paypal " option at Payment Instrument Type of Braintree.

**Comment by Taracque** [comment]
Ok, the problem can be, that the presentDropInPayment gets called before the initialize finishes. As those functions are async, please try the following:

```
BraintreePlugin.initialize(token,
	function() {
		console.log("init OK!");
		var options = {
			cancelText: "Cancel",
			title: "Purchase",
			ctaText: "Select Payment Method",
			amount: $rootScope.final_price,
			primaryDescription: "Your Item",
			secondaryDescription: "Free shipping!"
		};

		BraintreePlugin.presentDropInPaymentUI(options, function(result) {
			console.log(result);
			if (result.userCancelled) {
				console.debug("User cancelled payment dialog.");
			} else {
			   // my other tasks
			}
		});
	},
    function(error) { console.error(error); }
);
```

**Comment by championboylay** [comment]
Thanks for your support **Taracque**.
Finally I used [https://github.com/Taracque/cordova-plugin-braintree](https://github.com/Taracque/cordova-plugin-braintree) and it is solved the issue.
