### ISSUE TITLE
How my Users are logged in to Braintree...?

### ISSUE THREAD

**Issue by lse123** [Justin-Credible/cordova-plugin-braintree#24]
This Plugin if installed in my Android and iOS App --- what required from Users to pay eg 5$...? Must have Braintree Android App... ? How they are logged in to Braintree...?

**Comment by Justin-Credible** [comment]
I ended up using the JavaScript version of the Braintree SDK in my project, and therefore have never gotten back to finishing this plugin. Please check out the fork by Taracque, which is located at: https://github.com/Taracque/cordova-plugin-braintree
