### ISSUE TITLE
Switch to static framework for iOS

### ISSUE THREAD

**Issue by Justin-Credible** [Justin-Credible/cordova-plugin-braintree#3]
We are currently using several hacks (including a forked version of `node-xcode`, see #2) to get the iOS version of the libraries included into the XCode project.

Once Braintree offers a static SDK download we should integrate it and remove the hacks we are using. We are waiting on braintree/braintree_ios#148 for that.

**Comment by sornon1** [comment]
Hey @Justin-Credible, we updated the issue for this with [this guide](https://github.com/braintree/braintree_ios/blob/master/Docs/Braintree-Static-Integration-Guide.md). Hopefully this solves it for you!

**Comment by kimosabi77** [comment]
@Justin-Credible First off thank you for providing this plugin.

I attempted a cordova braintree plaugin about 8 months ago, works fine, but not as neat as yours. https://github.com/kimosabi77/braintree-cordova-plugin

Just in case anyone has the same issues for iOS as I had running your version, I was getting a crash error (lldb) on "could not find rpath/Braintree ...."

I had to make sure that I added all of the braintree frameworks under the "Embedded Binaries" section under Targets-> My App -> General

Once I added them in it ran fine. 
<img width="832" alt="screen shot 2016-07-27 at 3 17 11 pm" src="https://cloud.githubusercontent.com/assets/863269/17164675/db2c3ee8-540d-11e6-826a-a68a328cff42.png">

**Comment by mikegleasonjr** [comment]
I have to add the binaries as embedded too, is there a way to configure that through config.xml so I don't have to do it everytime I start from scratch?

**Comment by Taracque** [comment]
Try this in plugin.xml:
        <framework src="lib/ios/BraintreeVenmo.framework" custom="true" embed="true" />
        <framework src="lib/ios/BraintreeUI.framework" custom="true" embed="true" />
        <framework src="lib/ios/BraintreePayPal.framework" custom="true" embed="true" />
        <framework src="lib/ios/BraintreeDataCollector.framework" custom="true" embed="true" />
        <framework src="lib/ios/BraintreeCore.framework" custom="true" embed="true" />
        <framework src="lib/ios/BraintreeCard.framework" custom="true" embed="true" />
        <framework src="lib/ios/BraintreeApplePay.framework" custom="true" embed="true" />
        <framework src="lib/ios/Braintree3DSecure.framework" custom="true" embed="true" />

If that doesn't work, you need to add a hook for that (see: Check https://github.com/Taracque/cordova-plugin-braintree/tree/master/hooks)
Original idea: http://stackoverflow.com/questions/36650522/custom-cordova-plugin-add-framework-to-embedded-binaries

**Comment by Justin-Credible** [comment]
The new build hook takes care of adding the framework bundles as embedded binaries. It also adds a Copy Files build phase to ensure you don't have to manually add it yourself.

While Braintree still does not provide a pre-built binary (something like `libBraintree.a`), we can continue to use the committed Framework bundles built from Carthage and embed them with the build script.

Thanks for the information in this issue, it helped me when re-working the build script.

**Comment by Taracque** [comment]
I've built the frameworks directly from Braintree SDK. Check my fork, it has version 4.7.2 (iOS: https://github.com/Taracque/cordova-plugin-braintree/tree/master/lib/ios)

**Comment by mikegleasonjr** [comment]
@Taracque couldn't use your fork, I always get "Error: Path must be a string. Received undefined" when building. here's the full stack trace:

```
Error: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at searchPathForFile (
/plugins/cordova-plugin-braintree/node_modules/xcode/lib/pbxProject.js:1532:24)
    at pbxProject.removeFromFrameworkSearchPaths (/plugins/cordova-plugin-braintree/node_modules/xcode/lib/pbxProject.js:1050:20)
    at pbxProject.removeFramework (/plugins/cordova-plugin-braintree/node_modules/xcode/lib/pbxProject.js:322:14)
    at pbxProject.<anonymous> (/plugins/cordova-plugin-braintree/hooks/before_prepare.js:56:24)
    at emitTwo (events.js:106:13)
    at pbxProject.emit (events.js:191:7)
    at pbxProject.<anonymous> (/plugins/cordova-plugin-braintree/node_modules/xcode/lib/pbxProject.js:31:18)
    at emitTwo (events.js:106:13)
```

Sorry to hijack the thread but there's no issue in your repo!

**Comment by Taracque** [comment]
Do you have xcode npm module installed? Try 
` npm i xcode
